name: "Greet Contributors"

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet the contributor"
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello there, thanks for opening your first issue. We welcome you to the community!"
          pr-message: "Hello there, thanks for opening your first Pull Request. Someone will review it soon."
